---
app_layout:
  # Page 1: Apple
  -
    # Most Useful Apps
    - Calculator
    - Safari
    - iMovie
    - iTunes
    - iBooks
    - App Store
    - System Preferences

    # iWork
    - folder_title: iWork
      folder_layout:
        -
          - Pages
          - Numbers
          - Keynote

    # Apps
    - folder_title: Apps
      folder_layout:
        -
          - Mail
          - Contacts
          - Calendar
          - Reminders
          - Notes
          - Maps
          - Messages
          - FaceTime
          - Photo Booth
          - Photos
          # El Capitain specific
          - Game Center
          - Preview
          - Dictionary
          # Sierra specific
          # - Siri
          - Mission Control
          - Dashboard

    # Other Utilities
    - folder_title: Other
      folder_layout:
        -
          - QuickTime Player
          - TextEdit
          - Grapher
          - DVD Player
          - Time Machine
          - Font Book
          - Chess
          - Stickies
          - Image Capture
          - VoiceOver Utility
          - AirPort Utility
          - Migration Assistant
          - Terminal
          - Activity Monitor
          - Console
          - Keychain Access
          - System Information
          - Automator
          - Script Editor
          # Sierra specific
          # - Disk Utility
          - Boot Camp Assistant
          - Digital Color Meter
          - ColorSync Utility
          - Grab
          - Bluetooth File Exchange
          - Audio MIDI Setup
          # El Capitain specific
          - X11
          - Disk Utility

  # Page 2: General
  -
    - 1Password 6
    - Android File Transfer
    - World Clock

    # File Management
    - AppCleaner
    - DaisyDisk
    - Entropy
    - ForkLift

    # Social
    - Skype
    - Slack
    - Textual
    - Twitter

    # Internet
    - Google Chrome
    - Firefox
    - Transmission

    # Media Playback & Entertainment
    - Cog
    - Spotify
    - MPlayerX
    - OpenEmu

    - folder_title: Utilities
      folder_layout:
        -
          - BestRes
          - BetterSnapTool
          - BootChamp
          - Dropbox
          - Flux
          - Focus
          - Gmail Notifier
          - iStat Mini
          - OneDrive

  # Page 3: Productivity
  -
    # Media Creation
    - Affinity Designer
    - Affinity Photo
    - ScreenFlow

    # GTD
    - Clear

    # Microsoft Office
    - Microsoft Excel
    - Microsoft Word
    - folder_title: Microsoft Office (Other)
      folder_layout:
        -
          - Microsoft OneNote
          - Microsoft Outlook
          - Microsoft PowerPoint

    # Development
    - Dash
    - Kitematic (Beta)
    - MacDown
    - SourceTree
    - Sublime Text
    - VirtualBox
    - VMware Fusion


  # Page 4: Audio Software
  -
    # DAWs
    - Ableton Live 9 Suite
    - Cubase 9
    - Logic Pro X

    # Tools
    - Audio Hijack
    - Melodyne singletrack
    - ocenaudio
    - XLD

    # Hardware
    - Focusrite Control
    - ReMOTESLEditor

    # Software Managers
    - folder_title: Software Managers
      folder_layout:
        -
          - iLok License Manager
          - eLicenser Control Center
          - Native Access
          - Sonalksis Plugin Manager

    # Native Instruments
    - folder_title: Native Instruments (Other)
      folder_layout:
        -
          - Absynth 5
          - Battery 4
          - Controller Editor
          - FM8
          - Guitar Rig 5
          - Komplete Kontrol
          - Kontakt 5
          - Massive
          - Reaktor 6
          - ServiceCenter

widget_layout:
  -
    - Ski Report
    - Calculator
    - Calendar
    - Contacts
    - Dictionary
    - ESPN
    - Flight Tracker
    - Movies
    - Stickies
    - Stocks
    - Tile Game
    - Translation
    - Unit Converter
    - Weather
    - Web Clip
    - World Clock
