---
# Files
- name: create the directory to store the file
  file: path={{ item.dest | dirname }} state=directory
  when: item.dest != '/' and item.dest != '~'
  with_items: "{{ files }}"

- name: install the file requested
  copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode | default('0644') }}
  with_items: "{{ files }}"

# Symbolic Links
- name: check health of requested symlinks
  stat: path="{{ item.dest }}"
  register: symlink_health_check
  with_items: "{{ symbolic_links }}"

- name: clean up any files which are not symlinks
  file: path="{{ item.1.dest }}" state=absent
  when: symlink_health_check.results[item.0].stat.exists and
        not symlink_health_check.results[item.0].stat.islnk
  with_indexed_items: "{{ symbolic_links }}"

- name: symlink file to requested destination
  file:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
    state: link
  with_items: "{{ symbolic_links }}"
