---
- name: install vim
  homebrew: name=vim install_options=with-lua state=latest

- name: create the vim colors directory
  file: path={{ item }} state=directory mode=0755
  with_items:
    - ~/.vim
    - ~/.vim/bundle

- name: install vundle package manager
  git: repo=https://github.com/gmarik/Vundle.vim.git dest=~/.vim/bundle/Vundle.vim

- name: install vimrc to the home directory
  copy: src=vim/.vimrc dest=~ mode=0644

- name: install all vim plugins using vundle
  command: vim +PluginInstall +qall
  changed_when: false
