---
software_brew_casks:
  # General Software

  # Fonts
  - font-source-code-pro
  - font-source-code-pro-for-powerline

  # Freeware
  - android-file-transfer
  - appcleaner
  - bestres
  - bootchamp
  - cog
  - dropbox
  - firefox
  - flux
  - gmail-notifier
  - google-chrome
  - macdown
  - mplayerx
  - openemu-experimental
  - skype
  - slack
  - sourcetree
  - transmission
  - vagrant
  - virtualbox
  - xld

  # Commercial
  - 1password
  - audio-hijack
  - daisydisk
  - dash
  - entropy
  - focus
  - forklift-beta
  - microsoft-office
  - textual
  - vmware-fusion

  # Music Production Software

  # DAWs, Tools & Drivers
  - ableton-live-9-suite
  - audiomove
  - celemony-melodyne-editor
  - focusrite-control
  - native-instruments-native-access
  - novation-remote-sl-template-editor
  - ocenaudio
  - steinberg-cubase-pro-9
  - steinberg-cubase-pro-9-update

  # Plug-ins (Effect)
  - artsacoustic-reverb
  - audio-damage-eos
  - cableguys-filtershaper
  - cableguys-volumeshaper
  - cytomic-the-drop
  - cytomic-the-glue
  - dada-life-sausage-fattener
  - dmgaudio-compassion
  - dmgaudio-dualism
  - dmgaudio-equilibrium
  - dmgaudio-essence
  - dmgaudio-expurgate
  - dmgaudio-limitless
  - dmgaudio-pitchfunk
  - dmgaudio-trackcontrol
  - dmgaudio-trackds
  - dmgaudio-trackgate
  - dmgaudio-tracklimit
  - dmgaudio-trackmeter
  - eventide-2016-stereo-room
  - focusrite-red-plugin-suite
  - goodhertz-canopener-studio
  - illformed-glitch
  - native-instruments-driver
  - native-instruments-guitar-rig-5
  - native-instruments-rc-24
  - native-instruments-rc-48
  - native-instruments-replika-xt
  - native-instruments-solid-bus-comp-fx
  - native-instruments-solid-dynamics-fx
  - native-instruments-solid-eq-fx
  - native-instruments-supercharger-gt
  - native-instruments-transient-master-fx
  - native-instruments-enhanced-eq
  - native-instruments-passive-eq
  - native-instruments-vari-comp
  - native-instruments-vc-160-fx
  - native-instruments-vc-2a-fx
  - native-instruments-vc-76-fx
  - relab-lx480-complete
  - softube-amp-room-essentials
  - softube-drawmer-s73
  - softube-fet-compressor
  - softube-fix-flanger-and-doubler
  - softube-saturation-knob
  - softube-tsar-1r
  - softube-tube-delay
  - sonalksis-studio-one-bundle
  - soundtoys-5
  - studio-devil-amp-modeler-pro
  - u-he-mfm2
  - u-he-satin
  - u-he-uhbik
  - valhalladsp-valhallaspacemodulator
  - valhalladsp-valhallavintageverb
  - voxengo-deft-compressor-au-aax
  - voxengo-deft-compressor-vst-vst3
  - voxengo-elephant-au-aax
  - voxengo-elephant-vst-vst3
  - voxengo-glisseq-au-aax
  - voxengo-glisseq-vst-vst3
  - voxengo-msed-au-aax
  - voxengo-msed-vst-vst3
  - voxengo-span-au-aax
  - voxengo-span-vst-vst3
  - voxengo-voxformer-au-aax
  - voxengo-voxformer-vst-vst3

  # Plug-ins (Instrument)
  - lennardigital-sylenth1
  - native-instruments-absynth-5
  - native-instruments-battery-4
  - native-instruments-fm8
  - native-instruments-komplete-kontrol
  - native-instruments-kontakt-5
  - native-instruments-massive
  - native-instruments-reaktor-6
  - novation-bass-station
  - reveal-sound-spire
  - spectrasonics-omnisphere
  - steinberg-padshop
  - steinberg-padshop-update
  - steinberg-retrologue
  - synapse-audio-dune
  - u-he-hive
  - u-he-zebra
  - xfer-records-serum
  - xfer-records-serum-update
  - xfer-records-serumfx-update

  # Guitar Rig Effects
  - native-instruments-rammfire
  - native-instruments-reflektor
  - native-instruments-traktors-12

  # Reaktor Effects
  - native-instruments-molekular
  - native-instruments-the-finger-r2
  - native-instruments-the-mouth

  # Reaktor Instruments
  - native-instruments-flesh
  - native-instruments-form
  - native-instruments-kontour
  - native-instruments-monark
  - native-instruments-polyplex
  - native-instruments-razor
  - native-instruments-reaktor-blocks
  - native-instruments-reaktor-factory-library
  - native-instruments-reaktor-prism
  - native-instruments-reaktor-spark-r2
  - native-instruments-rounds
  - native-instruments-skanner-xt
