---
software_brew_packages:
  # Unix Utilities
  - android-platform-tools
  - bash
  - cdiff
  - ctags
  - curl
  - duti
  - dockutil
  - dos2unix
  - ffmpeg
  - findutils
  - fish
  - git
  - gnu-sed
  - hugo
  - loginitems
  - mas
  - md5sha1sum
  - p7zip
  - rlwrap
  - rsync
  - sassc
  - shellcheck
  - tree
  - unrar
  - watch
  - wget
  - xz

  # Programming Languages
  - go
  - rbenv
  - ruby-build

  # Completions
  - bash-completion
  - vagrant-completion
  - ruby-completion
  - rake-completion
