---
# Set various defaults which will updat the relevant plist files
osapp_defaults:
  # --- OS X ---

  # System Preferences & Globals
  - domain: Apple Global Domain
    values:
      # General / Appearance / Use dark menu bar and Dock
      AppleInterfaceStyle: Dark
      # Keyboard / Keyboard / Key Repeat
      KeyRepeat: 2
      # Keyboard / Keyboard / Delay Until Repeat
      InitialKeyRepeat: 25
      # Keyboard / Keyboard / Use all F1, F2, etc. keys as standard function keys
      com.apple.keyboard.fnState: true
      # Keyboard / Text / Correct spelling automatically
      NSAutomaticSpellingCorrectionEnabled: false
      # Keyboard / Text / Use smart quotes and dashes
      NSAutomaticQuoteSubstitutionEnabled: false
      NSAutomaticDashSubstitutionEnabled: false
      # Keyboard / Shortcuts / Full Keyboard Access / All controls
      AppleKeyboardUIMode: 3
      # Mouse / Point & Click / Tracking
      com.apple.mouse.scaling: 1.0

      # Enable subpixel font rendering on non-Apple LCDs
      AppleFontSmoothing: 2
      # Expand the save panel by default
      NSNavPanelExpandedStateForSaveMode: true
      NSNavPanelExpandedStateForSaveMode2: true
      # Disable the character accent menu when holding down a key
      ApplePressAndHoldEnabled: false
  # System Preferences / Accessibility
  - domain: com.apple.universalaccess
    values:
      # Zoom / Use scroll gesture with modifier keys to zoom
      closeViewScrollWheelToggle: true
      # Display / Cursor size
      mouseDriverCursorSize: 1.25

  # System Preferences / Mouse
  - domain: com.apple.driver.AppleBluetoothMultitouch.mouse
    values:
      # Point & Click / Secondary click
      MouseButtonMode: TwoButton

  # Launch Services
  - domain: com.apple.LaunchServices
    values:
      # Disable the 'Are you sure you want to open this application?' dialog
      LSQuarantine: false

  # Login Window
  - domain: com.apple.loginwindow
    values:
      # Disable 'Reopen windows when logging back in' by default
      TALLogoutSavesState: false

  # Dock
  - domain: com.apple.dock
    values:
      # Set the icon size of dock items
      tilesize: 60
      # Enable magnificationn of icons
      magnification: true
      # Make hidden applications translucent in the dock
      showhidden: true

  # Finder
  - domain: com.apple.finder
    values:
      # View / Show Status Bar
      ShowStatusBar: true
      # Set the default Finder display mode to list
      FXPreferredViewStyle: Nlsv

  # Menu (Clock)
  - domain: com.apple.menuextra.clock
    values:
      # Open Date & Time Preferences... / Clock / Show date
      DateFormat: "EEE d MMM  h:mm a"

  # Symbolic Hot Keys
  - domain: com.apple.symbolichotkeys
    values:
      # Disable slow motion effects
      # (http://apple.stackexchange.com/questions/66433)
      AppleSymbolicHotKeys:
        34: { enabled: 0 }
        35: { enabled: 0 }
        37: { enabled: 0 }

  # Screen Capture
  - domain: com.apple.screencapture
    values:
      location: ~/Pictures/Screenshots

  # --- Apple Software ---

  # Safari
  - domain: com.apple.Safari
    values:
      # View / Show Status Bar
      ShowStatusBar: true

  # --- 3rd Party Software ---

  # 1Password
  - domain: com.agilebits.onepassword4
    values:
      WelcomeWindowShown: true
      LockOnMainAppExit: false
      LockOnIdle: true
      ShowRichIcons: true
      KeepHelperRunning: true
      UserMetricsSkippedNewsletterSignupKey: true
      CompletedEssentialSettings: true
  - domain: 2BUA8C4S2C.com.agilebits.onepassword4-helper
    values:
      autosave: false

  # Android File Transfer
  - domain: com.google.android.mtpviewer
    values:
      FirstRunShown: true

  # AppCleaner
  - domain: net.freemacsoft.AppCleaner
    values:
      SUEnableAutomaticChecks: true
      SUHasLaunchedBefore: true
      SUSendProfileInfo: false

  # Audio Hijack
  - domain: com.rogueamoeba.audiohijack3
    values:
      homeWindowShown: true
      # Setting the launch count to 2 skips the newsletter prompt
      launchCount: 2

  # BetterSnapTool
  - domain: com.hegenberg.BetterSnapTool
    values:
      BSTDidAlreadyLaunchOnElCapitan: true
      BSTDidAlreadyLaunchOnce: true
      BSTDidClickHighlightedMenuItem: true
      # General Settings / Start BetterSnapTool everytime your Mac starts up
      launchOnStartup: true
      # Customizations / Use rounded corners
      roundCorners: false
      # Customizations / Border-width
      previewBorderWidth: 0.0
      # Keyboard Shortcuts
      registeredHotkeys:
        # maximize
        '0':
          keyCode: 126
          modifiers: 8395008
        # left half
        '2':
          keyCode: 123
          modifiers: 8395008
        # right half
        '4':
          keyCode: 124
          modifiers: 8395008
        # restore old window position
        '10':
          keyCode: 125
          modifiers: 8395008
        # center on next monitor
        '18':
          keyCode: 37
          modifiers: 6400

  # Clear
  - domain: com.realmacsoftware.clear.mac
    container: com.realmacsoftware.clear.mac
    values:
      app.shown-welcome: true

  # DaisyDisk
  - domain: com.daisydiskapp.DaisyDiskStandAlone
    values:
      moveToApplicationsFolderAlertSuppress: true

  # Dash
  - domain: com.kapeli.dashdoc
    values:
      moveToApplicationsFolderAlertSuppress: true
      didSuppressDownloadDocsetsAlert: true
      DHNotificationNoDocsetsFound: true
      reorderDocsetsAlertSuppressed: true
      DHNotificationDocsetPressEnterOrClickIconTip: true
      noDocsetsFoundAlertSuppressed: true
      syncFolderPath: "{{ cloud_app_config_dir }}/Dash"
      snippetSQLPath: "{{ cloud_app_config_dir }}/Dash/library.dash"
      # Note that the following setting is required or Dash thinks it needs
      # to set everything up again
      migratedV2Prefs: true

  # Entropy
  - domain: com.eigenlogik.Entropy
    values:
      moveToApplicationsFolderAlertSuppress: true
      SUEnableAutomaticChecks: true
      SUSendProfileInfo: false
      # Extraction / Auto-extract on open
      AutoExtractOnOpen: true

  # f.lux
  - domain: org.herf.Flux
    values:
      moveToApplicationsFolderAlertSuppress: true
      lateColorTemp: 2400.0
      nightColorTemp: 2800.0
      dayColorTemp: 3200.0
      locationTextField: Melbourne, Australia
      locationType: L
      location: '-37.814107,144.963280'
      wakeTime: 480

  # MacDown
  - domain: com.uranusjr.macdown
    values:
      firstVersionInstalled: '749'
      SUEnableAutomaticChecks: true
      # General
      editorSyncScrolling: true
      # Markdown
      extensionTables: true
      extensionFencedCode: true
      extensionIntraEmphasis: true
      extensionStrikethough: true
      extensionAutolink: true
      # Editor
      editorBaseFontInfo:
        name: SourceCodePro-Regular
        size: 16.0
      editorStyleName: Solarized (Dark)
      editorLineSpacing: 2.0
      editorHorizontalInset: 15.0
      editorVerticalInset: 15.0
      editorMaximumWidth: 800.0
      editorConvertTabs: true
      editorCompleteMatchingCharacters: true
      editorInsertPrefixInBlock: true
      editorEnsuresNewlineAtEndOfFile: true
      editorAutoIncrementNumberedLists: true

      # Rendering
      htmlStyleName: GitHub2
      htmlSyntaxHighlighting: true
      htmlTaskList: true
      htmlDetectFrontMatter: true
      htmlDefaultDirectoryUrl: "{{ development_dir }}"

  # Mia for GMail
  - domain: com.sovapps.gmailnotifier
    values:
      # Preferences / Notifications
      notifications: true
      # Preferences / Black & white icons
      blackWhiteIcons: true
      # Preferences / Open at login
      openAtLogin: true
      # Preferences / Sound
      sound: Submarine

  # Microsoft Office
  - domain: ~/Library/Group Containers/UBF8T346G9.Office/com.microsoft.officeprefs.plist
    values:
      kCUIThemePreferencesThemeKeyPath: 0

  - domain: com.microsoft.Excel
    container: com.microsoft.Excel
    values:
      kSubUIAppCompletedFirstRunSetup1507: true

  - domain: com.microsoft.Word
    container: com.microsoft.Word
    values:
      kSubUIAppCompletedFirstRunSetup1507: true

  - domain: com.microsoft.Powerpoint
    container: com.microsoft.Powerpoint
    values:
      kSubUIAppCompletedFirstRunSetup1507: true

  - domain: com.microsoft.onenote.mac
    container: com.microsoft.onenote.mac
    values:
      kSubUIAppCompletedFirstRunSetup1507: true

  - domain: com.microsoft.Outlook
    container: com.microsoft.Outlook
    values:
      kSubUIAppCompletedFirstRunSetup1507: true

  # MPlayerX
  - domain: org.niltsh.MPlayerX
    values:
      SUSendProfileInfo: false
      SUEnableAutomaticChecks: true
      # General / Keep window on top / Never
      OnTopMode: 0

  # OpenEmu
  - domain: org.openemu.OpenEmu
    values:
      setupAssistantFinished: true
      SUEnableAutomaticChecks: true
      videoFilter: SABR
      fullScreen: true
      # databasePath: ~/Library/Application Support/OpenEmu/Game Library

  # Pixelmator
  - domain: com.pixelmatorteam.pixelmator
    container: com.pixelmatorteam.pixelmator
    values:
      DOCUMENT_WINDOW_INFOVIEW_IS_VISIBLE_KEY: true

  # SourceTree
  - domain: com.torusknot.SourceTreeNotMAS
    values:
      moveToApplicationsFolderAlertSuppress: true
      analyticsHasAgreed: false
      agreedToEULA: true
      showStagingTip: false
      showFileStatusViewOptionsTip: false
      SUEnableAutomaticChecks: true
      globalUserFullName: Fotis Gimian
      globalUserEmail: fgimiansoftware@gmail.com
      diffFontName: SourceCodePro-Regular
      diffFontSize: 13.0
      defaultFolder: "{{ development_dir }}"
      createBookmarksOnOpenRepo: false

  # Textual
  - domain: com.codeux.apps.textual
    values:
      'Theme -> Invert Sidebar Colors Preference Enabled': 0
      'Theme -> Name': 'resource:Sapientia'
      'Text Input Prompt Suppression -> theme_override_info': true
      'World Controller':
        clients:
        - autoConnect: True
          connectionName: freenode
          nickname: fgimian
          realName: Fotis Gimian
          serverAddress: chat.freenode.net
          username: fgimian
          channelList:
          - channelName: '#ansible'
          - channelName: '#chef'
          - channelName: '#puppet'
          - channelName: '#salt'
          - channelName: '#python'

  # Transmission
  - domain: org.m0k.transmission
    values:
      # Transfers / Trash original torrent files
      DeleteOriginalTorrent: true
      # Hide the legal disclaimer
      WarningLegal: false

  # Twitter
  - domain: com.twitter.twitter-mac
    container: com.twitter.twitter-mac
    values:
      # General / Font size / 16 pt
      FontSize1: 16
      # General / Theme / Dark Theme
      TMSelectedThemeIdentifier: com.twitter.twitter.themeIdentifiers.darkTheme

  # VMware Fusion
  - domain: com.vmware.fusion
    values:
      # Virtual Machine Library / View / Show items as icons
      PLInventoryWindowStylePref: 1
      # Preferences / General / Show in menu bar / Only when Fusion is running
      showStartMenu3: 2
